#!/bin/bash

# The main packages are pre-installed in the AMI# , so we are skipping it
#
# add any missing repo's
# sudo add-apt-repository -y ppa:sjinks/phalcon
# sudo add-apt-repository -y ppa:nginx/stable

# sudo apt-get update

# install all the packages
# sudo apt-get -y install nginx htop php5-fpm php5-cli php5-mysql gcc php-pear memcached git-flow ruby libtool openssl rsync curl make automake htop nmap unzip php5-phalcon memcached php5-mcrypt php5-memcached php5-memcache php5-curl

# sudo pecl install mongo
# sudo pecl install redis

#setup the main vhost
if [ ! -r /var/www ] ; then
    sudo mkdir /var/www
fi

# set the location to the php-ini
pecl config-set php_ini /etc/php5/fpm/php.ini

# copy default server files
cd $VOICEMACHINE
sudo rm /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default

sudo cp serverfiles/php.ini /etc/php5/fpm/php.ini
sudo cp serverfiles/php.ini /etc/php5/cli/php.ini
sudo cp serverfiles/www.conf /etc/php5/fpm/pool.d/www.conf
sudo cp serverfiles/nginx.conf /etc/nginx/nginx.conf
sudo cp serverfiles/.s3cfg /home/ubuntu/.s3cfg

chmod 777 $VOICEMACHINE/app/logs

# restart the webserver
sudo service php5-fpm restart
sudo service nginx restart

#install s3cmd
wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -
sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list
sudo apt-get update && sudo apt-get install s3cmd

